### ISSUE TITLE
not using GPU

### ISSUE THREAD

**Issue by akwin1234** [newgenai79/SadTalker_withRefVideo#1]
any idea how do fix that.
i have cuda 1.18 and i think program is lower how do i fix

**Comment by SirDuffy** [comment]
me the same. installed in an empty drive, but only using cpu not gpu? i have a nvidia and automatic or forge are working fine. Any fix for me?

**Comment by nitinmukesh** [comment]
@akwin1234 @SirDuffy 
Solution here
https://github.com/newgenai79/SadTalker_withRefVideo/issues/2

**Comment by newgenai79** [comment]
@akwin1234 @SirDuffy 

Please refer new video posted today.
